[tools]
go = "1.27.1"
clang-format = "19.1.7"
golangci-lint = "2.13.2"

[tool_alias]
clang-tidy = "github:cpp-linter/clang-tools-static-binaries"

[tools.clang-tidy]
version = "2026.09.01-5fb8802d"
matching = "clang-tidy-19_"
bin = "clang-tidy"

[tasks.lint]
run = "make lint"
description = "Run the project Go linter"
