# Development version of the beyla Dockerfile that compiles for coverage
# and allows retrieving coverage files.
# The production-ready minimal image is in the project root's dockerfile.
FROM golang:1.26.3@sha256:efaccb5b497e90df3ebe5216cc25cd9f98e73874e2d638b56e38d4a3f098c41c AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /

COPY internal/test/integration/components/obi/ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /src

# Copy the go manifests and source
COPY .git/ .git/
COPY bpf/ bpf/
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

# Build
RUN make compile-for-coverage

FROM scratch

# Copy the native executable into the containers
COPY --from=builder /src/bin/obi /obi
COPY --from=builder /ebpf_instrument_wrapper.sh /ebpf_instrument_wrapper.sh

WORKDIR /

ENTRYPOINT [ "/ebpf_instrument_wrapper.sh" ]
