FROM node:24-slim@sha256:e8e2e91b1378f83c5b2dd15f0247f34110e2fe895f6ca7719dbb780f929368eb

# Set the working directory to /build
WORKDIR /

# Copy the source code into the image for building
COPY internal/test/integration/components/nodejsdist .

# Install NodeJS express
RUN npm init -y && npm install express axios

EXPOSE 5006

# Run the node app
CMD [ "node", "service-r.js" ]
