# Dockerfile that will build a container that runs python with FastAPI and uvicorn on port 8080
FROM python:3.14@sha256:61346539f7b26521a230e72c11da5ebd872924745074b19736e7d65ba748c366
EXPOSE 8080
RUN apt update
RUN apt install -y libpq-dev
RUN pip install fastapi uvicorn gunicorn psycopg2
COPY main_ssl.py /main_ssl.py
COPY server.crt /server.crt
COPY server.key /server.key
CMD ["gunicorn", "--keyfile", "/server.key", "--certfile", "/server.crt", "-w", "3", "-b", "0.0.0.0:8080", "-k", "uvicorn.workers.UvicornWorker", "main_ssl:app"]
