FROM python:3.14@sha256:4b827abf32c14b7df9a0dc5199c2f0bc46e2c9862cd5d77eddae8a2cd8460f60
COPY internal/test/integration/components/python-app-net-metrics-client/main.py main.py
CMD ["python", "main.py"]