// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package rubytools // import "go.opentelemetry.io/obi/pkg/internal/rubytools"

import (
	"bufio"
	"regexp"
	"strings"

	"go.opentelemetry.io/obi/pkg/internal/langtools"
)

const maxRailsApplicationBytes int64 = 64 * 1024

var (
	acronymBoundary = regexp.MustCompile(`([A-Z\d]+)([A-Z][a-z])`)
	wordBoundary    = regexp.MustCompile(`([a-z\d])([A-Z])`)

	railsModuleDeclaration = regexp.MustCompile(
		`^\s*module\s+(?:::)?([A-Z][A-Za-z\d_]*(?:::[A-Z][A-Za-z\d_]*)*)\s*(?:#.*)?$`,
	)
	railsApplicationDeclaration = regexp.MustCompile(
		`^\s*class\s+((?:::)?[A-Z][A-Za-z\d_]*(?:::[A-Z][A-Za-z\d_]*)*)\s*<\s*(?:::)?Rails::Application\b`,
	)
)

func readRailsApplicationName(path string) string {
	file, _ := langtools.OpenMetadataFile(path, maxRailsApplicationBytes)
	if file == nil {
		return ""
	}
	defer file.Close()

	return scanRailsApplicationName(bufio.NewScanner(file))
}

// scanRailsApplicationName recognizes the conventional declaration generated by Rails. It is
// intentionally a heuristic: unusual Ruby metaprogramming falls back to the project directory.
func scanRailsApplicationName(scanner *bufio.Scanner) string {
	var module string
	for scanner.Scan() {
		line := scanner.Text()
		if match := railsModuleDeclaration.FindStringSubmatch(line); match != nil {
			module = match[1]
			continue
		}

		match := railsApplicationDeclaration.FindStringSubmatch(line)
		if match == nil {
			continue
		}

		class := strings.TrimPrefix(match[1], "::")
		if class == "Application" {
			return railsServiceName(module)
		}

		return railsServiceName(class)
	}

	return ""
}

func railsServiceName(className string) string {
	if className == "" {
		return ""
	}

	className = strings.TrimSuffix(className, "::Application")
	parts := strings.Split(className, "::")
	for index, part := range parts {
		part = acronymBoundary.ReplaceAllString(part, `${1}_${2}`)
		part = wordBoundary.ReplaceAllString(part, `${1}_${2}`)
		part = strings.ReplaceAll(part, "_", "-")
		parts[index] = strings.ToLower(part)
	}

	return strings.Join(parts, "/")
}
