# Build the Auto SDK activation fixture.
FROM golang:1.27.0@sha256:0ecdc2a9f6156af6451080bfe3d8382a662fcc4e209608c6f919e643453514c1 AS builder

ARG TARGETARCH

ENV GOARCH=$TARGETARCH

WORKDIR /src

COPY internal/test/integration/components/goautosdk/main.go .
COPY internal/test/integration/components/goautosdk/v1.33/go.mod .
COPY internal/test/integration/components/goautosdk/v1.33/go.sum .

RUN go build -o goautosdk .

FROM debian:bookworm-slim@sha256:74d56e3931e0d5a1dd51f8c8a2466d21de84a271cd3b5a733b803aa91abf4421

WORKDIR /
COPY --from=builder /src/goautosdk .
USER 0:0

CMD ["/goautosdk"]
