FROM mysql:8.0.43-debian@sha256:0d58619ea4f3eac1239eb28fabea6a3ac63a48f02b7c09432bcd8b9b1072103d

SHELL ["/bin/bash", "-c"]

RUN chmod 1777 /tmp
RUN usermod -u 1000 mysql
RUN groupmod -g 1000 mysql

COPY test/integration/components/php/unix_sock_sql/docker/init_sql/ /docker-entrypoint-initdb.d/
COPY test/integration/components/php/unix_sock_sql/config/mysql/custom.cnf /etc/mysql/conf.d/

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 3306

RUN chown -R mysql:mysql /var/lib/mysql

RUN install -o mysql -g mysql -d /var/log/mysql && \
    install -o mysql -g mysql /dev/null /var/log/mysql/error.log && \
    install -o mysql -g mysql /dev/null /var/log/mysql/slow.log

USER mysql
