FROM python:3.14@sha256:a2e9788143507cacbb754fcc06ad3b7108ca9c334f97a466906103846107cdd5
EXPOSE 8392

WORKDIR /app

# Reuses the pythonasync-uvloop lock file; this app needs a subset of it
COPY internal/test/integration/components/pythonasync-uvloop/requirements-3.9.txt .
RUN pip install --require-hashes -r requirements-3.9.txt

COPY internal/test/integration/components/pythonasync-common/cancelled_to_thread.py .
COPY internal/test/integration/components/pythonasync-generic .

CMD ["python", "async_server_test.py"]
