FROM eclipse-temurin:17@sha256:c2cf43dc9cc4ad9187f1dd7beda6466ad861e1dc30f5d27416ec5a0a3a4653b7 AS javabuilder

# Install tar and gzip to extract the Maven binaries
RUN apt install -y tar gzip

# Install Maven
ARG USER_HOME_DIR="/cache"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY test/integration/components/javakafka/.mvn .mvn/
COPY test/integration/components/javakafka/mvnw mvnw
COPY test/integration/components/javatestserver/src src/
COPY test/integration/components/javatestserver/pom.xml pom.xml

RUN java -version
RUN ./mvnw -version

# Build
RUN ./mvnw clean package

# The App Image
FROM eclipse-temurin:17-jre@sha256:a17a2d28a7100a63f512fb9db86fa3ce8d577f1e6f6abbf8da1cad1bf48ece87

EXPOSE 8085

# Copy the native executable into the containers
COPY --from=javabuilder /build/target/greeting-service-1.2.0.jar .
CMD [ "java", "-jar", "/greeting-service-1.2.0.jar" ]