FROM eclipse-temurin:17@sha256:dfed9396bc9ad962ba169f920625b675cae40102393c4dda95ce21d2f67faa3d AS javabuilder

# Install tar and gzip to extract the Maven binaries
RUN apt install -y tar gzip

# Install Maven
ARG USER_HOME_DIR="/cache"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY test/integration/components/javakafka/.mvn .mvn/
COPY test/integration/components/javakafka/mvnw mvnw
COPY test/integration/components/javatestserver/src src/
COPY test/integration/components/javatestserver/pom.xml pom.xml

RUN java -version
RUN ./mvnw -version

# Build
RUN ./mvnw clean package

# The App Image
FROM eclipse-temurin:17.0.16_8-jre@sha256:cc8d5734de13851eec02b00681685cb5cc05c42c73fed381a571d0cf8ca55d97

EXPOSE 8085

# Copy the native executable into the containers
COPY --from=javabuilder /build/target/greeting-service-1.2.0.jar .
CMD [ "java", "-jar", "/greeting-service-1.2.0.jar" ]