FROM python:3.14@sha256:7aea6827c8787754f99339ffed8cfc41fb09421f9c7d0e77a198b08422a3455e
EXPOSE 8080

WORKDIR /app

COPY internal/test/integration/components/memorybio/client.py .

CMD ["python", "client.py"]
