file_format: "1.0"
resource: {}
propagator: {}
tracer_provider:
    processors:
        - batch:
            exporter:
                otlp_grpc:
                    endpoint: ""
                    tls:
                        insecure: false
            max_queue_size: 16384
            schedule_delay: 15000
meter_provider:
    readers:
        - periodic:
            exporter:
                otlp_grpc:
                    default_histogram_aggregation: explicit_bucket_histogram
                    endpoint: ""
                    tls:
                        insecure: false
            interval: 60000
        - pull:
            exporter:
                prometheus/development:
                    port: 0
extensions:
    obi:
        version: "2.0"
        capture:
            policy:
                default_action: include
                match_order: first_match_wins
                min_process_age: 5s
                poll_interval: 0s
            rules:
                - action: exclude
                  name: exclude-otlp-exporters
                  description: ""
                  match:
                    process:
                        exports_otlp:
                            port: 4317
                            protocol: protobuf
                  refine: {}
                - action: exclude
                  name: exclude-linux-system-paths
                  description: ""
                  match:
                    process:
                        exe_path_glob:
                            - /lib/systemd/*
                  refine: {}
                - action: exclude
                  name: exclude-linux-system-paths
                  description: ""
                  match:
                    process:
                        exe_path_glob:
                            - /usr/lib/systemd/*
                  refine: {}
                - action: exclude
                  name: exclude-linux-system-paths
                  description: ""
                  match:
                    process:
                        exe_path_glob:
                            - /usr/libexec/*
                  refine: {}
                - action: exclude
                  name: exclude-linux-system-paths
                  description: ""
                  match:
                    process:
                        exe_path_glob:
                            - /sbin/*
                  refine: {}
                - action: exclude
                  name: exclude-linux-system-paths
                  description: ""
                  match:
                    process:
                        exe_path_glob:
                            - /usr/sbin/*
                  refine: {}
            instrumentation:
                couchbase:
                    db_cache_size: 1024
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                dns:
                    enabled:
                        metrics: true
                        traces: false
                    filters:
                        metrics: {}
                        traces: {}
                    request_timeout: 5s
                gpu:
                    enabled:
                        metrics: true
                        traces: false
                    enabled_mode: auto
                    filters:
                        metrics: {}
                        traces: {}
                grpc:
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                http:
                    buffer_size: 0
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                    payload_extraction:
                        enabled: []
                        enrichment:
                            policy:
                                default_action:
                                    body: exclude
                                    headers: exclude
                                obfuscation_string: '***'
                            rules: []
                        sqlpp:
                            endpoint_patterns:
                                - /query/service
                    request_timeout: 0s
                    routes:
                        discovery:
                            disabled_languages: []
                            java:
                                delay: 1m0s
                            timeout: 10s
                        ignore_mode: ""
                        ignored_patterns: []
                        max_path_segment_cardinality: 10
                        patterns: []
                        unmatched: heuristic
                        wildcard_char: '*'
                    track_request_headers: false
                kafka:
                    buffer_size: 0
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                    topic_uuid_cache_size: 1024
                mongo:
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                    requests_cache_size: 1024
                redis:
                    db_cache:
                        enabled: false
                        max_size: 1000
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                sql:
                    enabled:
                        metrics: true
                        traces: true
                    filters:
                        metrics: {}
                        traces: {}
                    heuristic_detect: false
                    mssql:
                        buffer_size: 0
                        prepared_statements_cache_size: 1024
                    mysql:
                        buffer_size: 0
                        prepared_statements_cache_size: 1024
                    postgres:
                        buffer_size: 0
                        prepared_statements_cache_size: 1024
            runtimes:
                go:
                    enabled: true
                    filter: {}
                java:
                    attach_timeout: 10s
                    debug:
                        bytecode_instrumentation: false
                        enabled: false
                    enabled: true
                    filter: {}
                nodejs:
                    enabled: true
                    filter: {}
            network:
                capture:
                    buffer_size: 0
                    diagnostics:
                        print_flows: false
                    enabled: false
                    endpoint_identity:
                        agent_ip: ""
                        agent_ip_family: any
                        agent_ip_interface: external
                    enrichment:
                        geo_ip:
                            cache:
                                size: 512
                                ttl: 1h0m0s
                            ipinfo:
                                path: ""
                            maxmind:
                                asn_path: ""
                                country_path: ""
                        reverse_dns:
                            cache:
                                size: 256
                                ttl: 1h0m0s
                            mode: none
                    filters:
                        metrics: {}
                        traces: {}
                    flow_lifecycle:
                        active_timeout: 5s
                        deduplication:
                            first_come_ttl: 0s
                            strategy: first_come
                        max_tracked_flows: 5000
                        sampling: 0
                    interface_discovery:
                        mode: watch
                        poll_interval: 10s
                    selection:
                        cidrs: []
                        direction: both
                        interfaces:
                            exclude:
                                - lo
                            include: []
                        protocols:
                            exclude: []
                            include: []
                    source: socket_filter
                stats:
                    diagnostics:
                        print_stats: false
                    endpoint_identity:
                        agent_ip: ""
                        agent_ip_family: any
                        agent_ip_interface: external
                    enrichment:
                        geo_ip:
                            cache:
                                size: 512
                                ttl: 1h0m0s
                            ipinfo:
                                path: ""
                            maxmind:
                                asn_path: ""
                                country_path: ""
                        reverse_dns:
                            cache:
                                size: 256
                                ttl: 1h0m0s
                            mode: none
                    selection:
                        cidrs: []
            limits:
                metric_span_names: 100
                network_packets: 5000
            engine:
                batching:
                    batch_length: 100
                    batch_timeout: 1s
                    wakeup_len: 500
                bpf_filesystem:
                    path: /sys/fs/bpf/
                debug:
                    bpf: false
                    protocol_print: false
                maps:
                    global_scale_factor: 0
                pid_filter:
                    disabled: false
                propagation:
                    context_propagation: disabled
                    disable_black_box_cp: false
                    override_bpfloop_enabled: false
                traffic:
                    control_backend: auto
                    force_map_reader: auto
                    high_request_volume: false
                transactions:
                    max_duration: 5m0s
            safety:
                enforce_system_capabilities: false
            channels:
                buffer_len: 50
                panic_on_send_timeout: false
                send_timeout: 1m0s
            telemetry:
                metrics:
                    reporters_cache_len: 256
                    ttl: 5m0s
                traces:
                    reporters_cache_len: 256
        enrich:
            attributes:
                extra_group_attributes: {}
                metadata_retry:
                    max_interval: 5s
                    start_interval: 500ms
                    timeout: 30s
                select: {}
            enrichers:
                kubernetes:
                    auth:
                        kubeconfig_path: ""
                    cluster_name: ""
                    drop_external: false
                    informers:
                        disabled: []
                        initial_sync_timeout: 30s
                        reconnect_initial_interval: 5s
                        resync_period: 30m0s
                    metadata_cache:
                        address: ""
                        restrict_local_node: false
                        source_labels:
                            service_name: ""
                            service_namespace: ""
                    mode: autodetect
                    resource_labels:
                        service.name:
                            - app.kubernetes.io/instance
                            - app.kubernetes.io/name
                        service.namespace:
                            - app.kubernetes.io/part-of
                        service.version:
                            - app.kubernetes.io/version
                    service_name_template: ""
            service_name:
                cache:
                    size: 1024
                    ttl: 5m0s
                sources:
                    - k8s
                unresolved_hosts:
                    names:
                        default: unresolved
                        incoming: incoming
                        outgoing: outgoing
        correlation:
            log_trace_annotation:
                async_writer:
                    channel_len: 500
                    workers: 8
                cache:
                    size: 128
                    ttl: 30m0s
                enabled: false
                filter: {}
        daemon:
            internal_metrics:
                bpf:
                    scrape_interval: 15s
                exporter: disabled
                prometheus:
                    path: /internal/metrics
                    port: 0
            logging:
                debug_trace_output: disabled
                format: ""
                level: INFO
            profiling:
                port: 0
            shutdown:
                timeout: 10s
            telemetry:
                metrics:
                    prometheus:
                        allow_service_graph_self_references: false
                        extra_resource_attributes: []
                        extra_span_resource_attributes: []
                        span_metrics_service_cache_size: 10000
