#!/usr/bin/env bash
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
#
# Release-driven schema versioning. Reads the OBI release version from
# versions.yaml and, for that version:
#   1. cuts site/schemas/obi/<version> (previous published file plus a new,
#      empty <version>: entry on top — a cumulative superset, like semconv),
#   2. bumps the emitted schema_url constant (OBISchemaURL) and the weaver
#      registry manifest schema_url to <version>.
#
# Intended to run at release prep (invoked by `make prerelease`). Files are
# immutable once published: if telemetry changed in this release, add the
# rename entries by hand under the new <version>: block before committing
# (see site/README.md).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_URL="https://open-telemetry.github.io/opentelemetry-ebpf-instrumentation/schemas/obi"
SCHEMA_DIR="$ROOT/site/schemas/obi"
SCHEMA_VERSION_FILE="$ROOT/pkg/export/attributes/names/schema_version.go"
MANIFEST="$ROOT/schemas/obi/manifest.yaml"

fail() { echo "generate-schema-next: $1" >&2; exit 1; }

version="$(awk '/^  obi:/{o=1} o&&/version:/{v=$2; sub(/^v/,"",v); print v; exit}' "$ROOT/versions.yaml")"
[ -n "$version" ] || fail "could not read the obi version from versions.yaml"
echo "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || fail "versions.yaml obi version '$version' is not MAJOR.MINOR.PATCH"

new_file="$SCHEMA_DIR/$version"
if [ -f "$new_file" ]; then
	echo "generate-schema-next: schema file for $version already exists — leaving it (preserving any hand-added transformations)"
else
	prev="$(printf '%s\n' "$SCHEMA_DIR"/* | sed 's#.*/##' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)"
	[ -n "$prev" ] || fail "no previous schema file under $SCHEMA_DIR to base $version on"
	grep -Eq '^versions:[[:space:]]*$' "$SCHEMA_DIR/$prev" || fail "previous file $prev has no 'versions:' block"
	{
		echo "file_format: 1.1.0"
		echo "schema_url: $BASE_URL/$version"
		echo "versions:"
		echo "  $version:"
		awk 'f{print} /^versions:[[:space:]]*$/{f=1}' "$SCHEMA_DIR/$prev"
	} > "$new_file"
	echo "generate-schema-next: created site/schemas/obi/$version (empty transformations; add renames by hand if telemetry changed)"
fi

# Regenerate the emitted URL constant and bump the registry manifest to <version>.
cat > "$SCHEMA_VERSION_FILE" <<EOF
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by scripts/generate-schema-next.sh; DO NOT EDIT.

package attr

var OBISchemaURL = "$BASE_URL/$version"
EOF
perl -i -pe "s#\\Q$BASE_URL/\\E[0-9]+\\.[0-9]+\\.[0-9]+#$BASE_URL/$version#g" "$MANIFEST"
echo "generate-schema-next: OBISchemaURL and manifest schema_url set to $version"
