# Renders the OBI telemetry reference from `weaver registry resolve` output.
# Selects the page with --arg page (readme|attributes|metrics).
#
# Resolution merges the upstream semconv registry declared in
# schemas/obi/manifest.yaml, so groups are restricted to the ones whose
# provenance is OBI's own registry. Matching on group id is not enough: OBI
# defines metrics whose ids carry no `obi` marker (the spanmetrics,
# service-graph and target.info families).
#
# Briefs are upstream prose that may contain bare URLs or `*`, so the generated
# pages disable the two markdownlint rules that would flag them.

def is_obi: (.lineage.provenance.schema_url // "") | test("opentelemetry-ebpf-instrumentation");
def cell: (. // "") | tostring | gsub("\n"; " ") | gsub("\\|"; "\\|") | sub("^ +"; "") | sub(" +$"; "");
def attr_type: if (.type | type) == "string" then .type else "enum" end;

# An enum's value space is the documentation, so surface its members. Upstream
# enums run long (db.system.name has 42), which would make the table unreadable,
# so the list is capped. Declared examples win when present.
def enum_members_shown: 8;
def values:
  if ((.examples // []) | length) > 0 then ((.examples // []) | map(tostring) | join("; "))
  elif (.type | type) == "object" then
    ((.type.members // []) | map(.value // .id | tostring)) as $m
    | if ($m | length) == 0 then ""
      elif ($m | length) > enum_members_shown then (($m[0:enum_members_shown] | join("; ")) + "; …")
      else ($m | join("; "))
      end
  else "" end;

# Deprecations are declared in the registry but were invisible here, so a reader
# could pick a renamed metric as if it were current.
def deprecation:
  if (.deprecated // null) == null then ""
  else
    (.deprecated.reason // "deprecated") as $reason
    | if (.deprecated.renamed_to // "") != "" then "**\($reason)** — use `\(.deprecated.renamed_to)` instead"
      else "**\($reason)**" + (if (.deprecated.note // "") != "" then " — \(.deprecated.note)" else "" end)
      end
  end;

def obi_groups($type): [.groups[] | select(.type == $type) | select(is_obi)];
def attr_groups: obi_groups("attribute_group") | sort_by(.id);
def metrics: obi_groups("metric") | sort_by(.metric_name);

def attr_rows:
  [.attributes[]?
   | ((deprecation | cell) as $dep
      | (if $dep == "" then (.brief | cell) else "\($dep). \(.brief | cell)" end) as $desc
      | "| `\(.name)` | \(attr_type) | \(.stability | cell) | \($desc) | \(values | cell) |")]
  | sort;

def attr_table:
  if (attr_rows | length) == 0 then ["No attributes."]
  else ["| Attribute | Type | Stability | Description | Examples |", "| --- | --- | --- | --- | --- |"] + attr_rows
  end;

def page($title; $intro; $items):
  ["<!-- NOTE: THIS FILE IS AUTOGENERATED by `make generate-schema-docs`. DO NOT EDIT BY HAND. -->",
   "<!-- markdownlint-disable MD034 MD037 -->",
   "",
   "# \($title)",
   ""]
  + $intro
  + ($items | flatten)
  | join("\n");

def attributes_page:
  page("OBI attributes";
    ["Attributes that OpenTelemetry eBPF Instrumentation defines in addition to the",
     "[upstream semantic conventions](https://opentelemetry.io/docs/specs/semconv/) it is built",
     "against. Attributes OBI emits that are defined upstream are documented there, not here.",
     "Which attributes appear on a given signal depends on the enabled features and on",
     "`attributes.select`; these lists are the full set OBI may attach, not a mandatory minimum."];
    [attr_groups[] | ["", "## `\(.id)`", "", (.brief | cell), ""] + attr_table]);

def metrics_page:
  page("OBI metrics";
    ["Metrics that OpenTelemetry eBPF Instrumentation defines and emits itself. Which of these",
     "are produced depends on the enabled metrics features."];
    [metrics[] | ["", "## `\(.metric_name)`", ""]
                 + (if (deprecation | cell) == "" then [] else ["> \(deprecation | cell)", ""] end)
                 + [(.brief | cell), "",
                  "| Instrument | Unit | Stability |", "| --- | --- | --- |",
                  "| \(.instrument | cell) | \(if (.unit // "") == "" then "1" else .unit end | cell) | \(.stability | cell) |",
                  ""] + attr_table]);

def readme_page:
  page("OBI telemetry reference";
    ["Generated from the OBI semantic-convention registry in `schemas/obi/`.",
     "",
     "- [Attributes](attributes.md) — \(attr_groups | length) attribute groups",
     "- [Metrics](metrics.md) — \(metrics | length) metrics",
     "",
     "The telemetry schema OBI stamps on its telemetry as `schema_url` is published",
     "alongside these docs under `../schemas/obi/`."];
    []);

if $page == "attributes" then attributes_page
elif $page == "metrics" then metrics_page
else readme_page
end
