# Renders the OBI telemetry reference from `weaver registry resolve --v2` output.
# Selects the page with --arg page (readme|attributes|metrics|spans).
#
# Resolution merges the upstream semconv registry declared in
# schemas/obi/manifest.yaml, so signals are restricted to the ones this
# registry defines: an imported upstream signal names the upstream schema url
# as its provenance source, a local one names none. Matching on name is not
# enough: OBI defines metrics whose names carry no `obi` marker (the
# spanmetrics, service-graph and target.info families).
#
# Briefs are upstream prose that may contain bare URLs or `*`, so the generated
# pages disable the two markdownlint rules that would flag them.

def is_obi: (.provenance.source // "") == "";
def cell: (. // "") | tostring | gsub("\n"; " ") | gsub("\\|"; "\\|") | sub("^ +"; "") | sub(" +$"; "");
def attr_type: if (.type | type) == "string" then .type else "enum" end;
def canonical_scalar: if type == "number" and . == floor then (floor | tostring) else tostring end;

# An enum's value space is the documentation, so surface its members. Upstream
# enums run long (db.system.name has 42), which would make the table unreadable,
# so the list is capped. Declared examples win when present.
def enum_members_shown: 8;
# `examples` is a list in most declarations but a bare scalar in some upstream
# ones, so it is coerced before use rather than iterated blindly.
def examples_list: (.examples // []) | if type == "array" then . else [.] end;
def values:
  if (examples_list | length) > 0 then (examples_list | map(canonical_scalar) | join("; "))
  elif (.type | type) == "object" then
    ((.type.members // []) | map(.value // .id | canonical_scalar)) as $m
    | if ($m | length) == 0 then ""
      elif ($m | length) > enum_members_shown then (($m[0:enum_members_shown] | join("; ")) + "; …")
      else ($m | join("; "))
      end
  else "" end;

# Deprecations are declared in the registry but were invisible here, so a reader
# could pick a renamed metric as if it were current.
def deprecation:
  if (.deprecated // null) == null then ""
  else
    (.deprecated.reason // "deprecated") as $reason
    | if (.deprecated.renamed_to // "") != "" then "**\($reason)** — use `\(.deprecated.renamed_to)` instead"
      else "**\($reason)**" + (if (.deprecated.note // "") != "" then " — \(.deprecated.note)" else "" end)
      end
  end;

# Internal attribute groups, which only share an attribute set between signals,
# are not part of the resolved registry, so every group here is public.
def attr_groups: [.registry.attribute_groups[] | select(is_obi)] | sort_by(.id);
def metrics: [.registry.metrics[] | select(is_obi)] | sort_by(.name);
def spans: [.registry.spans[] | select(is_obi)] | sort_by(.type);

def description:
  ((deprecation | cell) as $dep
   | if $dep == "" then (.brief | cell) else "\($dep). \(.brief | cell)" end);

def attr_rows:
  [.attributes[]? | "| `\(.key)` | \(attr_type) | \(.stability | cell) | \(description) | \(values | cell) |"]
  | sort;

def attr_table:
  if (attr_rows | length) == 0 then ["No attributes."]
  else ["| Attribute | Type | Stability | Description | Examples |", "| --- | --- | --- | --- | --- |"] + attr_rows
  end;

# A requirement level belongs to a carrier, not to a definition, so it is
# rendered on the metric and span pages and not on the attributes page. An
# absent level is weaver's default.
def req_level:
  (.requirement_level // "recommended")
  | if type == "object"
    then (to_entries[0] | "`\(.key)`: \(.value | cell)")
    else "`\(. | cell)`"
    end;

def carrier_rows:
  [.attributes[]? | "| `\(.key)` | \(attr_type) | \(req_level) | \(.stability | cell) | \(description) | \(values | cell) |"]
  | sort;

def carrier_table:
  if (carrier_rows | length) == 0 then ["No attributes."]
  else ["| Attribute | Type | Requirement level | Stability | Description | Examples |",
        "| --- | --- | --- | --- | --- | --- |"] + carrier_rows
  end;

def page($title; $intro; $items):
  ["<!-- NOTE: THIS FILE IS AUTOGENERATED by `make generate-schema-docs`. DO NOT EDIT BY HAND. -->",
   "<!-- markdownlint-disable MD034 MD037 -->",
   "",
   "# \($title)",
   ""]
  + $intro
  + ($items | flatten)
  | join("\n");

def attributes_page:
  page("OBI attributes";
    ["Attributes that OpenTelemetry eBPF Instrumentation defines in addition to the",
     "[upstream semantic conventions](https://opentelemetry.io/docs/specs/semconv/) it is built",
     "against. Attributes OBI emits that are defined upstream are documented there, not here.",
     "Which attributes appear on a given signal depends on the enabled features and on",
     "`attributes.select`; these lists are the full set OBI may attach, not a mandatory minimum."];
    [attr_groups[] | ["", "## `\(.id)`", "", (.brief | cell), ""] + attr_table]);

def metrics_page:
  page("OBI metrics";
    ["Metrics that OpenTelemetry eBPF Instrumentation defines and emits itself. Which of these",
     "are produced depends on the enabled metrics features.",
     "",
     "OBI also emits some metrics defined upstream, unchanged — the Node.js event-loop and V8",
     "families among them. Those are imported rather than redeclared, so they are documented in",
     "the [upstream semantic conventions](https://opentelemetry.io/docs/specs/semconv/) and are",
     "not listed or counted here."];
    [metrics[] | ["", "## `\(.name)`", ""]
                 + (if (deprecation | cell) == "" then [] else ["> \(deprecation | cell)", ""] end)
                 + [(.brief | cell), "",
                  "| Instrument | Unit | Stability |", "| --- | --- | --- |",
                  "| \(.instrument | cell) | \(if (.unit // "") == "" then "1" else .unit end | cell) | \(.stability | cell) |",
                  ""] + carrier_table]);

def spans_page:
  page("OBI spans";
    ["Spans that OpenTelemetry eBPF Instrumentation emits, grouped by the shape OBI produces",
     "for each protocol it recognises. The span kind is part of the contract; which attributes",
     "appear depends on the enabled features and on `attributes.select`."];
    [spans[] | ["", "## `\(.type)`", ""]
               + (if (deprecation | cell) == "" then [] else ["> \(deprecation | cell)", ""] end)
               + [(.brief | cell), "",
                "| Span kind | Stability |", "| --- | --- |",
                "| \(.kind | cell) | \(.stability | cell) |",
                ""] + carrier_table]);

def readme_page:
  page("OBI telemetry reference";
    ["Generated from the OBI semantic-convention registry in `schemas/obi/`.",
     "",
     "- [Attributes](attributes.md) — \(attr_groups | length) attribute groups",
     "- [Metrics](metrics.md) — \(metrics | length) metrics",
     "- [Spans](spans.md) — \(spans | length) spans",
     "",
     "Counts cover what OBI defines. Metrics OBI emits unchanged from upstream are imported",
     "rather than redeclared and are documented upstream.",
     "",
     "The telemetry schema OBI stamps on its telemetry as `schema_url` is published",
     "alongside these docs under `../schemas/obi/`."];
    []);

if $page == "attributes" then attributes_page
elif $page == "metrics" then metrics_page
elif $page == "spans" then spans_page
else readme_page
end
