ARG JRE_IMAGE=eclipse-temurin:25.0.3_9-jre@sha256:7ea65de6187ad8fbcc0ad155950c38664a7371148bb3ccf1ec1e1b286b44ad08

FROM eclipse-temurin:25@sha256:dfc0093e3dbf43dae57827111c6e374f5b44fac19a9451584b2b336b81474d64 AS javabuilder

# Install tar and gzip to extract the Maven binaries
RUN apt install -y tar gzip

# Install Maven
ARG USER_HOME_DIR="/cache"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY internal/test/integration/components/javakafka/.mvn .mvn/
COPY internal/test/integration/components/javakafka/mvnw mvnw
COPY internal/test/integration/components/javatestserver/src src/
COPY internal/test/integration/components/javatestserver/pom.xml pom.xml

RUN java -version
RUN ./mvnw -version

# Build
RUN ./mvnw clean package

# The App Image
FROM ${JRE_IMAGE}

EXPOSE 8085

# Copy the native executable into the containers
COPY --from=javabuilder /build/target/greeting-service-1.2.0.jar .
CMD [ "java", "-jar", "/greeting-service-1.2.0.jar" ]