FROM ruby:3.0.2@sha256:15dd21ae353c5f4faebed038d9d131c47b9fd84c14be8c3cfbc750204b63f009 AS builder

WORKDIR /build

ENV BUNDLE_PATH=/usr/local/bundle

COPY internal/test/integration/components/rubytestserver/testapi .
COPY internal/test/integration/components/rubytestserver/testapi_compat/Gemfile_ruby302_puma5 Gemfile
COPY internal/test/integration/components/rubytestserver/testapi_compat/Gemfile_ruby302_puma5.lock Gemfile.lock

RUN gem install bundler -v 2.2.22
RUN bundle _2.2.22_ install
RUN bundle exec rake app:update:bin
RUN bundle exec rake db:migrate

FROM ruby:3.0.2-slim@sha256:9c4076bcc90de736bca3419299cf7b5e5ce0c83d659bad4c1f88a1ad8ca6dbf4

WORKDIR /

ENV BUNDLE_PATH=/usr/local/bundle

COPY --from=builder /build .
COPY --from=builder /usr/local/bundle /usr/local/bundle

EXPOSE 3040

CMD [ "bundle", "exec", "rails", "server", "-p", "3040", "-b", "0.0.0.0" ]
