// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package integration

import (
	"fmt"
	"net/http"
	"path"
	"testing"
	"time"

	json "github.com/goccy/go-json"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/obi/internal/test/integration/components/docker"
	"go.opentelemetry.io/obi/internal/test/integration/components/jaeger"
	ti "go.opentelemetry.io/obi/pkg/test/integration"
)

const (
	staticTraceID = "12345678901234567890123456789012" // Easy to spot
	staticSpanID  = "0000000000000001"                 // Span ID in the static traceparent
	// the test client increments the span ID by 0x10 before injecting
	staticSpanIDSentByA = "0000000000000011"
	forwardedSpanID     = "1111111111111111"                 // Span ID used in forwarded traceparent
	scraperTraceID      = "abcdefabcdefabcdefabcdefabcdef12" // Trace reused across every scrape
	scraperSpanID       = "2222222222222222"                 // Span ID reused across every scrape
	scrapeBurstLen      = 15
)

// TestTraceparentExtraction validates that the eBPF tpinjector correctly:
// 1. Extracts existing Traceparent headers from HTTP requests
// 2. Uses the extracted trace ID instead of generating a new one
// 3. Only injects Traceparent when one doesn't already exist
func TestTraceparentExtraction(t *testing.T) {
	compose, err := docker.ComposeSuite("docker-compose-tpclient.yml", path.Join(pathOutput, "test-suite-traceparent.log"))
	require.NoError(t, err)
	compose.Env = append(compose.Env, `OTEL_EBPF_EXECUTABLE_PATH=`, `OTEL_EBPF_OPEN_PORT=`)
	require.NoError(t, compose.Up())

	// Wait for service to be ready
	waitForTestComponents(t, "http://localhost:6000")

	// Wait for instrumentation to be ready
	t.Log("waiting for instrumentation to be ready")
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		ti.DoHTTPGet(ct, "http://localhost:6000/smoke", 200)

		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&limit=1")
		if err != nil || resp == nil || resp.StatusCode != http.StatusOK {
			return
		}

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		if len(tq.Data) == 0 {
			return
		}
	}, 2*time.Minute, 1*time.Second)
	t.Log("instrumentation ready")

	t.Run("without_traceparent", testWithoutTraceparent)
	t.Run("with_traceparent", testWithTraceparent)
	t.Run("with_forwarded_traceparent", testWithForwardedTraceparent)
	t.Run("scraper_burst_never_joins_reused_trace", testScraperBurstNeverJoinsReusedTrace)

	runWeaverValidation(t)

	require.NoError(t, compose.Close())
}

// testWithoutTraceparent validates that when NO Traceparent header is present,
// eBPF generates a new trace ID and propagates it through the chain
func testWithoutTraceparent(t *testing.T) {
	// Trigger /no-tp endpoint - starts chain: a -> b -> c
	// Each service makes client call WITHOUT traceparent (eBPF should generate and propagate)
	ti.DoHTTPGet(t, "http://localhost:6000/no-tp", 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&operation=GET%20%2Fno-tp")
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		traces := tq.FindBySpan(jaeger.Tag{Key: "url.path", Type: "string", Value: "/no-tp"})
		require.GreaterOrEqual(ct, len(traces), 1)
		trace = traces[0]
		require.NotEmpty(ct, trace.Spans)
	}, testTimeout, 100*time.Millisecond)

	// Validate the trace has spans from all 3 services (a, b, c)
	serviceASpans := trace.FindByOperationName("GET /no-tp", "server")
	require.GreaterOrEqual(t, len(serviceASpans), 1)
	serviceASpan := serviceASpans[0]

	// Should have a trace ID (generated by eBPF)
	require.NotEmpty(t, serviceASpan.TraceID)
	require.Len(t, serviceASpan.TraceID, 32) // 16 bytes in hex = 32 characters

	// Should NOT be the static trace ID (since we didn't send one)
	require.NotEqual(t, staticTraceID, serviceASpan.TraceID,
		"eBPF should generate a new trace ID, not use the static one")

	// Verify all spans in the trace share the same trace ID (context propagation)
	for _, span := range trace.Spans {
		require.Equal(t, serviceASpan.TraceID, span.TraceID,
			"All spans in chain should share the same generated trace ID")
	}
}

// testWithTraceparent validates that when a Traceparent header IS present,
// eBPF extracts and uses the existing trace ID (no generation)
func testWithTraceparent(t *testing.T) {
	// Trigger /with-tp endpoint - starts chain: a -> b -> c
	// Each service makes client call WITH static traceparent (eBPF should extract and propagate)
	ti.DoHTTPGet(t, "http://localhost:6000/with-tp", 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		// Query by static trace ID
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&traceID=" + staticTraceID)
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		require.GreaterOrEqual(ct, len(tq.Data), 1, "should find trace with static trace ID")
		trace = tq.Data[0]
		require.NotEmpty(ct, trace.Spans)
	}, testTimeout, 100*time.Millisecond)

	// CRITICAL: All spans must have the static trace ID, proving extraction worked
	for _, span := range trace.Spans {
		require.Equal(t, staticTraceID, span.TraceID,
			"eBPF should extract and use the static Traceparent trace ID (12345...) for all spans in chain")
	}

	// Verify we have spans from all 3 services in the chain
	require.GreaterOrEqual(t, len(trace.Spans), 3,
		"Should have spans from all services in the chain (a, b, c)")

	// wire left untouched, so the callee still parents to the app's span
	serviceBServerSpans := trace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-b", "server")
	require.GreaterOrEqual(t, len(serviceBServerSpans), 1, "should find tpclient-b server span")
	requireChildOfSpanID(t, serviceBServerSpans[0], staticSpanIDSentByA,
		"tpclient-b server span should parent to the span tpclient-a put on the wire")

	serviceBClientSpans := trace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-b", "client")
	require.GreaterOrEqual(t, len(serviceBClientSpans), 1, "should find tpclient-b client span")
	requireChildOfReference(t, serviceBClientSpans[0], serviceBServerSpans[0],
		"tpclient-b client span should keep the matching in-process parent")

	// unverifiable on egress: the client span stays in the inbound trace
	require.Empty(t, trace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-a", "client"),
		"tpclient-a client span must not join a trace the app injected on egress")

	ownTrace := findTraceExcluding(t, "GET%20%2Fwith-tp", staticTraceID)
	logTraceShape(t, "tpclient-a own trace", ownTrace)

	serviceAServerSpans := ownTrace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-a", "server")
	require.GreaterOrEqual(t, len(serviceAServerSpans), 1, "should find tpclient-a server span")
	serviceAClientSpans := ownTrace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-a", "client")
	require.GreaterOrEqual(t, len(serviceAClientSpans), 1, "should find tpclient-a client span")

	requireDescendantOf(t, ownTrace, serviceAClientSpans[0], serviceAServerSpans[0],
		"tpclient-a client span should stay under its own server span")
}

// testWithForwardedTraceparent validates that when the SAME Traceparent is forwarded
// unchanged through the chain (proxy scenario), eBPF detects this and overrides the span ID
func testWithForwardedTraceparent(t *testing.T) {
	// Trigger /with-forwarded-tp endpoint - starts chain: a -> b -> c
	// Each service forwards the SAME static traceparent (simulating a proxy)
	// eBPF should detect that span_id matches parent_id and override it
	ti.DoHTTPGet(t, "http://localhost:6000/with-forwarded-tp", 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		// Query by static trace ID
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&traceID=" + staticTraceID)
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))

		// Find traces with /with-forwarded-tp operations
		traces := tq.FindBySpan(jaeger.Tag{Key: "url.path", Type: "string", Value: "/with-forwarded-tp"})
		require.GreaterOrEqual(ct, len(traces), 1, "should find trace with forwarded traceparent")
		trace = traces[0]
		require.NotEmpty(ct, trace.Spans)
	}, testTimeout, 100*time.Millisecond)

	// CRITICAL: All spans must have the static trace ID (extraction worked)
	for _, span := range trace.Spans {
		require.Equal(t, staticTraceID, span.TraceID,
			"eBPF should extract and use the static trace ID even for forwarded traceparents")
	}

	// CRITICAL: Span IDs should NOT all be the forwarded span ID (1111111111111111)
	// eBPF should detect the forwarding pattern and override with generated span IDs
	allSpansHaveForwardedID := true
	for _, span := range trace.Spans {
		if span.SpanID != forwardedSpanID {
			allSpansHaveForwardedID = false
			break
		}
	}
	require.False(t, allSpansHaveForwardedID,
		"eBPF should override forwarded span IDs (not all spans should have %s)", forwardedSpanID)

	// Verify we have spans from all 3 services in the chain
	require.GreaterOrEqual(t, len(trace.Spans), 3,
		"Should have spans from all services in the chain (a, b, c)")
}

// a scraper reusing one traceparent must never pull our spans into its trace
func testScraperBurstNeverJoinsReusedTrace(t *testing.T) {
	ti.DoHTTPGet(t, fmt.Sprintf("http://localhost:6000/scrape-burst?n=%d", scrapeBurstLen), 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-b&traceID=" + scraperTraceID)
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		require.GreaterOrEqual(ct, len(tq.Data), 1, "should find the scraper trace")
		trace = tq.Data[0]

		serverSpans := trace.FindByOperationNameServiceAndKind("GET /scraped", "tpclient-b", "server")
		require.GreaterOrEqual(ct, len(serverSpans), scrapeBurstLen, "every scrape must reach the callee")
	}, testTimeout, 100*time.Millisecond)

	// the app's own propagation: none of it may be a root we introduced
	spanIDs := map[string]struct{}{}
	for _, span := range trace.Spans {
		require.Equal(t, scraperTraceID, span.TraceID)

		requireChildOfSpanID(t, span, scraperSpanID,
			"span %q must parent to the reused header span, never become a root of the app's trace",
			span.OperationName)

		_, dup := spanIDs[span.SpanID]
		require.False(t, dup, "span IDs within the scraper trace must be unique")
		spanIDs[span.SpanID] = struct{}{}
	}

	require.Empty(t, trace.FindByOperationNameServiceAndKind("GET /scraped", "tpclient-a", "client"),
		"the scraper's own client spans must not join the trace it keeps reusing")

	// every scrape stays under the request that triggered the burst
	ownTrace := findTraceExcluding(t, "GET%20%2Fscrape-burst", scraperTraceID)
	burstServerSpans := ownTrace.FindByOperationNameServiceAndKind("GET /scrape-burst", "tpclient-a", "server")
	require.GreaterOrEqual(t, len(burstServerSpans), 1, "should find the tpclient-a server span for the burst")
	scrapeClientSpans := ownTrace.FindByOperationNameServiceAndKind("GET /scraped", "tpclient-a", "client")
	require.GreaterOrEqual(t, len(scrapeClientSpans), scrapeBurstLen, "all scrapes must be captured")

	for _, span := range scrapeClientSpans {
		requireDescendantOf(t, ownTrace, span, burstServerSpans[0],
			"each scrape must stay under the request that made it")
	}
}

// server spans export "in queue"/"processing" children, so calls hang off "processing"
func requireDescendantOf(t *testing.T, trace jaeger.Trace, child, ancestor jaeger.Span, msgAndArgs ...any) {
	t.Helper()

	current := child

	for range len(trace.Spans) {
		parent, ok := trace.ParentOf(&current)
		if !ok {
			break
		}

		if parent.SpanID == ancestor.SpanID {
			return
		}

		current = parent
	}

	require.Fail(t, "span does not descend from the expected ancestor", msgAndArgs...)
}

func logTraceShape(t *testing.T, label string, trace jaeger.Trace) {
	t.Helper()

	t.Logf("%s: traceID=%s spans=%d", label, trace.TraceID, len(trace.Spans))

	for _, span := range trace.Spans {
		parent := "<root>"
		for _, ref := range span.References {
			if ref.RefType == "CHILD_OF" {
				parent = ref.SpanID
			}
		}
		kind, _ := jaeger.FindIn(span.Tags, "span.kind")
		t.Logf("  span=%s parent=%s kind=%v op=%q svc=%s",
			span.SpanID, parent, kind.Value, span.OperationName,
			trace.Processes[span.ProcessID].ServiceName)
	}
}

// the trace OBI resolved itself, not the one the app injected
func findTraceExcluding(t *testing.T, operation, excludedTraceID string) jaeger.Trace {
	t.Helper()

	var found jaeger.Trace

	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&operation=" + operation)
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))

		for _, tr := range tq.Data {
			if tr.TraceID != excludedTraceID && len(tr.Spans) > 0 {
				found = tr
				return
			}
		}

		require.Fail(ct, "no trace of OBI's own making found", "operation=%s", operation)
	}, testTimeout, 100*time.Millisecond)

	return found
}

func requireChildOfSpanID(t *testing.T, child jaeger.Span, parentSpanID string, msgAndArgs ...any) {
	t.Helper()

	for _, ref := range child.References {
		if ref.RefType == "CHILD_OF" {
			require.Equal(t, parentSpanID, ref.SpanID, msgAndArgs...)
			return
		}
	}
	require.Fail(t, "no CHILD_OF reference found", msgAndArgs...)
}

func requireChildOfReference(t *testing.T, child, parent jaeger.Span, msgAndArgs ...any) {
	t.Helper()

	for _, ref := range child.References {
		if ref.RefType == "CHILD_OF" {
			require.Equal(t, parent.SpanID, ref.SpanID, msgAndArgs...)
			return
		}
	}
	require.Fail(t, "missing CHILD_OF reference", msgAndArgs...)
}
