// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package integration

import (
	"fmt"
	"io"
	"net"
	"net/http"
	"path"
	"strings"
	"testing"
	"time"

	json "github.com/goccy/go-json"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/obi/internal/test/integration/components/docker"
	"go.opentelemetry.io/obi/internal/test/integration/components/jaeger"
	ti "go.opentelemetry.io/obi/pkg/test/integration"
)

const (
	staticTraceID           = "12345678901234567890123456789012" // Easy to spot
	staticHugeTPTraceID     = "aabbccddeeff00112233445566778899" // Distinct ID for the HTTP huge-headers sub-test
	staticBoundaryTPTraceID = "deadbeefcafe00112233445566778899" // Distinct ID for the chunk-boundary sub-test
	forwardedSpanID         = "1111111111111111"                 // Span ID used in forwarded traceparent

	// traceparentChunkBoundary is the number of filler bytes that places the
	// traceparent header exactly at byte offset 956 of the TCP stream.
	//
	// Derivation:
	//   k_tp_chunk_step = TRACE_BUF_SIZE - TRACE_PARENT_HEADER_LEN = 1024 - 68 = 956
	//   HTTP overhead before the traceparent header line:
	//     "GET /with-huge-tp HTTP/1.1\r\n" = 28 bytes
	//     "Host: localhost:6000\r\n"        = 22 bytes
	//     "X-Filler: <filler>\r\n" prefix  = 10 + 2 = 12 bytes
	//     ─────────────────────────────────────────────────
	//     total fixed overhead              = 62 bytes
	//   fillerSize = 956 - 62 = 894
	//
	// With fillerSize=894 the eBPF strstr guard (index >= 956) skips the
	// traceparent in chunk 0; it is found at local index 0 of chunk 1.
	traceparentChunkBoundary = 894
)

// TestTraceparentExtraction validates that the eBPF tpinjector correctly:
// 1. Extracts existing Traceparent headers from HTTP requests
// 2. Uses the extracted trace ID instead of generating a new one
// 3. Only injects Traceparent when one doesn't already exist
func TestTraceparentExtraction(t *testing.T) {
	compose, err := docker.ComposeSuite("docker-compose-tpclient.yml", path.Join(pathOutput, "test-suite-traceparent.log"))
	require.NoError(t, err)
	compose.Env = append(compose.Env, `OTEL_EBPF_EXECUTABLE_PATH=`, `OTEL_EBPF_OPEN_PORT=`)
	require.NoError(t, compose.Up())

	// Wait for all services to be ready.
	waitForTestComponents(t, "http://localhost:6000")

	// Wait for instrumentation to be ready
	t.Log("waiting for instrumentation to be ready")
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		ti.DoHTTPGet(ct, "http://localhost:6000/smoke", 200)

		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&limit=1")
		if err != nil || resp == nil || resp.StatusCode != http.StatusOK {
			return
		}

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		if len(tq.Data) == 0 {
			return
		}
	}, 2*time.Minute, 1*time.Second)
	t.Log("instrumentation ready")

	t.Run("without_traceparent", testWithoutTraceparent)
	t.Run("with_traceparent", testWithTraceparent)
	t.Run("with_forwarded_traceparent", testWithForwardedTraceparent)
	t.Run("with_huge_headers_traceparent", testWithHugeHeadersTraceparent)
	t.Run("with_traceparent_at_chunk_boundary", testWithTraceparentAtChunkBoundary)

	runWeaverValidation(t)

	require.NoError(t, compose.Close())
}

// testWithoutTraceparent validates that when NO Traceparent header is present,
// eBPF generates a new trace ID and propagates it through the chain
func testWithoutTraceparent(t *testing.T) {
	// Trigger /no-tp endpoint - starts chain: a -> b -> c
	// Each service makes client call WITHOUT traceparent (eBPF should generate and propagate)
	ti.DoHTTPGet(t, "http://localhost:6000/no-tp", 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&operation=GET%20%2Fno-tp")
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		traces := tq.FindBySpan(jaeger.Tag{Key: "url.path", Type: "string", Value: "/no-tp"})
		require.GreaterOrEqual(ct, len(traces), 1)
		trace = traces[0]
		require.NotEmpty(ct, trace.Spans)
	}, testTimeout, 100*time.Millisecond)

	// Validate the trace has spans from all 3 services (a, b, c)
	serviceASpans := trace.FindByOperationName("GET /no-tp", "server")
	require.GreaterOrEqual(t, len(serviceASpans), 1)
	serviceASpan := serviceASpans[0]

	// Should have a trace ID (generated by eBPF)
	require.NotEmpty(t, serviceASpan.TraceID)
	require.Len(t, serviceASpan.TraceID, 32) // 16 bytes in hex = 32 characters

	// Should NOT be the static trace ID (since we didn't send one)
	require.NotEqual(t, staticTraceID, serviceASpan.TraceID,
		"eBPF should generate a new trace ID, not use the static one")

	// Verify all spans in the trace share the same trace ID (context propagation)
	for _, span := range trace.Spans {
		require.Equal(t, serviceASpan.TraceID, span.TraceID,
			"All spans in chain should share the same generated trace ID")
	}
}

// testWithTraceparent validates that when a Traceparent header IS present,
// eBPF extracts and uses the existing trace ID (no generation)
func testWithTraceparent(t *testing.T) {
	// Trigger /with-tp endpoint - starts chain: a -> b -> c
	// Each service makes client call WITH static traceparent (eBPF should extract and propagate)
	ti.DoHTTPGet(t, "http://localhost:6000/with-tp", 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		// Query by static trace ID
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&traceID=" + staticTraceID)
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))
		require.GreaterOrEqual(ct, len(tq.Data), 1, "should find trace with static trace ID")
		trace = tq.Data[0]
		require.NotEmpty(ct, trace.Spans)
	}, testTimeout, 100*time.Millisecond)

	// CRITICAL: All spans must have the static trace ID, proving extraction worked
	for _, span := range trace.Spans {
		require.Equal(t, staticTraceID, span.TraceID,
			"eBPF should extract and use the static Traceparent trace ID (12345...) for all spans in chain")
	}

	// Verify we have spans from all 3 services in the chain
	require.GreaterOrEqual(t, len(trace.Spans), 3,
		"Should have spans from all services in the chain (a, b, c)")

	serviceAClientSpans := trace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-a", "client")
	require.GreaterOrEqual(t, len(serviceAClientSpans), 1, "should find tpclient-a client span")
	requireNoChildOfReference(t, serviceAClientSpans[0],
		"tpclient-a client span should not inherit a parent from the generated server trace")

	serviceBServerSpans := trace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-b", "server")
	require.GreaterOrEqual(t, len(serviceBServerSpans), 1, "should find tpclient-b server span")
	serviceBClientSpans := trace.FindByOperationNameServiceAndKind("GET /with-tp", "tpclient-b", "client")
	require.GreaterOrEqual(t, len(serviceBClientSpans), 1, "should find tpclient-b client span")
	requireChildOfReference(t, serviceBClientSpans[0], serviceBServerSpans[0],
		"tpclient-b client span should keep the matching in-process parent")
}

// testWithForwardedTraceparent validates that when the SAME Traceparent is forwarded
// unchanged through the chain (proxy scenario), eBPF detects this and overrides the span ID
func testWithForwardedTraceparent(t *testing.T) {
	// Trigger /with-forwarded-tp endpoint - starts chain: a -> b -> c
	// Each service forwards the SAME static traceparent (simulating a proxy)
	// eBPF should detect that span_id matches parent_id and override it
	ti.DoHTTPGet(t, "http://localhost:6000/with-forwarded-tp", 200)

	var trace jaeger.Trace
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		// Query by static trace ID
		resp, err := http.Get(jaegerQueryURL + "?service=tpclient-a&traceID=" + staticTraceID)
		require.NoError(ct, err)
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))

		// Find traces with /with-forwarded-tp operations
		traces := tq.FindBySpan(jaeger.Tag{Key: "url.path", Type: "string", Value: "/with-forwarded-tp"})
		require.GreaterOrEqual(ct, len(traces), 1, "should find trace with forwarded traceparent")
		trace = traces[0]
		require.NotEmpty(ct, trace.Spans)
	}, testTimeout, 100*time.Millisecond)

	// CRITICAL: All spans must have the static trace ID (extraction worked)
	for _, span := range trace.Spans {
		require.Equal(t, staticTraceID, span.TraceID,
			"eBPF should extract and use the static trace ID even for forwarded traceparents")
	}

	// CRITICAL: Span IDs should NOT all be the forwarded span ID (1111111111111111)
	// eBPF should detect the forwarding pattern and override with generated span IDs
	allSpansHaveForwardedID := true
	for _, span := range trace.Spans {
		if span.SpanID != forwardedSpanID {
			allSpansHaveForwardedID = false
			break
		}
	}
	require.False(t, allSpansHaveForwardedID,
		"eBPF should override forwarded span IDs (not all spans should have %s)", forwardedSpanID)

	// Verify we have spans from all 3 services in the chain
	require.GreaterOrEqual(t, len(trace.Spans), 3,
		"Should have spans from all services in the chain (a, b, c)")
}

func requireNoChildOfReference(t *testing.T, span jaeger.Span, msgAndArgs ...any) {
	t.Helper()

	for _, ref := range span.References {
		require.NotEqual(t, "CHILD_OF", ref.RefType, msgAndArgs...)
	}
}

func requireChildOfReference(t *testing.T, child, parent jaeger.Span, msgAndArgs ...any) {
	t.Helper()

	for _, ref := range child.References {
		if ref.RefType == "CHILD_OF" {
			require.Equal(t, parent.SpanID, ref.SpanID, msgAndArgs...)
			return
		}
	}
	require.Fail(t, "missing CHILD_OF reference", msgAndArgs...)
}

// sendRawRequest writes a raw HTTP/1.1 GET request over a plain TCP connection.
// The header order is fully controlled by the caller, which is not guaranteed by
// net/http (headers are sorted alphabetically before being written to the wire).
// The response is drained and the connection is closed before returning.
func sendRawRequest(addr, urlPath string, fillerSize int, traceparent string) error {
	conn, err := net.DialTimeout("tcp", addr, 5*time.Second)
	if err != nil {
		return err
	}
	defer conn.Close()

	var sb strings.Builder
	fmt.Fprintf(&sb, "GET %s HTTP/1.1\r\n", urlPath)
	fmt.Fprintf(&sb, "Host: %s\r\n", addr)
	fmt.Fprintf(&sb, "X-Filler: %s\r\n", strings.Repeat("X", fillerSize))
	fmt.Fprintf(&sb, "traceparent: %s\r\n", traceparent)
	sb.WriteString("Connection: close\r\n")
	sb.WriteString("\r\n")

	if _, err = io.WriteString(conn, sb.String()); err != nil {
		return err
	}
	// Drain the response so the server has time to process the request before
	// the connection is closed. A deadline avoids blocking forever if the server
	// does not honor Connection: close.
	if err = conn.SetDeadline(time.Now().Add(10 * time.Second)); err != nil {
		return err
	}
	_, err = io.ReadAll(conn)
	return err
}

// testWithTraceparentAtChunkBoundary validates that the eBPF chunked tail-call
// parser finds the traceparent header when it is placed exactly at the chunk
// boundary (byte offset 956 of the TCP stream). This is the case where the eBPF
// strstr guard (index >= TRACE_BUF_SIZE - TRACE_PARENT_HEADER_LEN = 956) skips
// the header in chunk 0 and it is only found at local index 0 of chunk 1.
func testWithTraceparentAtChunkBoundary(t *testing.T) {
	tp := "00-" + staticBoundaryTPTraceID + "-0000000000000001-01"
	err := sendRawRequest("localhost:6000", "/with-huge-tp", traceparentChunkBoundary, tp)
	require.NoError(t, err)

	assertHugeHeadersTraceparent(t, hugeHeadersCase{
		jaegerService: "tpclient-a",
		chainServices: []string{"tpclient-a", "tpclient-b", "tpclient-c"},
		traceID:       staticBoundaryTPTraceID,
		urlPath:       "/with-huge-tp",
	})
}

// testWithHugeHeadersTraceparent validates that when a large filler header (>2KB)
// precedes the Traceparent header, the eBPF chunked tail-call parser still finds it.
func testWithHugeHeadersTraceparent(t *testing.T) {
	req, err := http.NewRequest(http.MethodGet, "http://localhost:6000/with-huge-tp", nil)
	require.NoError(t, err)
	// Header name is chosen so it sorts before "Traceparent" alphabetically.
	// net/http writes request headers in sorted order, so this guarantees the
	// filler precedes the traceparent on the wire and forces the chunked parser path.
	req.Header.Set("big-filler", strings.Repeat("X", 2500))
	req.Header.Set("traceparent", "00-"+staticHugeTPTraceID+"-0000000000000001-01")

	resp, err := http.DefaultClient.Do(req)
	require.NoError(t, err)
	require.Equal(t, http.StatusOK, resp.StatusCode)
	require.NoError(t, resp.Body.Close())

	assertHugeHeadersTraceparent(t, hugeHeadersCase{
		jaegerService: "tpclient-a",
		chainServices: []string{"tpclient-a", "tpclient-b", "tpclient-c"},
		traceID:       staticHugeTPTraceID,
		urlPath:       "/with-huge-tp",
	})
}

// hugeHeadersCase holds the parameters that vary across the huge-headers
// traceparent sub-tests. jaegerService is the entry service of the chain.
// chainServices lists every service expected to contribute a server span;
// the assertion verifies each one is present so a partial trace (e.g. only
// tpclient-a showed up) is detected and retried.
type hugeHeadersCase struct {
	jaegerService string
	chainServices []string
	traceID       string
	urlPath       string
}

// assertHugeHeadersTraceparent polls Jaeger until the expected trace appears
// and asserts that every span in the chain carries the static trace ID,
// proving the eBPF parser found the traceparent even when it was buried
// after 2KB+ of filler headers.
func assertHugeHeadersTraceparent(t *testing.T, c hugeHeadersCase) {
	t.Helper()
	opName := "GET " + c.urlPath
	require.EventuallyWithT(t, func(ct *assert.CollectT) {
		resp, err := http.Get(jaegerQueryURL + "?service=" + c.jaegerService + "&traceID=" + c.traceID)
		require.NoError(ct, err)
		defer resp.Body.Close()
		require.Equal(ct, http.StatusOK, resp.StatusCode)

		var tq jaeger.TracesQuery
		require.NoError(ct, json.NewDecoder(resp.Body).Decode(&tq))

		traces := tq.FindBySpan(jaeger.Tag{Key: "url.path", Type: "string", Value: c.urlPath})
		require.GreaterOrEqual(ct, len(traces), 1,
			"should find trace with huge headers + traceparent for service %s", c.jaegerService)

		// Iterate all returned traces to find the first one where every chain
		// service has contributed a server span. Using traces[0] unconditionally
		// risks a false positive when Jaeger returns a stale complete trace from
		// a previous run alongside the current one (same static trace ID).
		var trace *jaeger.Trace
		for i := range traces {
			tr := &traces[i]
			allPresent := true
			for _, svc := range c.chainServices {
				found := false
				for _, span := range tr.FindByOperationName(opName, "server") {
					if proc, ok := tr.Processes[span.ProcessID]; ok && proc.ServiceName == svc {
						found = true
						break
					}
				}
				if !found {
					allPresent = false
					break
				}
			}
			if allPresent {
				trace = tr
				break
			}
		}
		require.NotNil(ct, trace,
			"no complete trace found with all chain services for traceID %s", c.traceID)

		for _, span := range trace.Spans {
			require.Equal(ct, c.traceID, span.TraceID,
				"eBPF parser should extract the static trace ID even when buried after 2KB+ of headers")
		}
	}, testTimeout, 100*time.Millisecond)
}
