// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"io"
	"math"
	"sort"
	"strings"
)

const (
	maxFlakyTestsShown    = 20
	maxRecentFailuresShown = 30
)

func writeReport(w io.Writer, results []TestResult, repo string) error {
	if len(results) == 0 {
		_, err := fmt.Fprintln(w, "# CI Test Analysis Report\n\nNo test data found for the analysis period.")
		return err
	}

	minDate, maxDate := dateRange(results)
	tests := computeTestStats(results)
	workflows := computeWorkflowStats(results)
	fingerprints := computeFingerprintStats(results)

	runIDs := map[string]bool{}
	for _, r := range results {
		runIDs[r.RunID] = true
	}

	p := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# CI Test Analysis Report")
	p("")
	p("**Period:** %s to %s", minDate, maxDate)
	p("**Runs analyzed:** %d | **Tests tracked:** %d", len(runIDs), len(tests))
	p("")

	writeWorkflowTable(w, p, workflows)
	flakyTests := writeFlakyTestsTable(w, p, tests)
	writeFingerprintTable(w, p, fingerprints)
	writeRecentFailuresTable(w, p, results, repo)

	flakyCount := len(flakyTests)
	p("---")
	p("*Generated by CI Test Analysis · %d tests analyzed · %d flaky (%.0f%%)*",
		len(tests), flakyCount, float64(flakyCount)/math.Max(float64(len(tests)), 1)*100)

	return nil
}

func writeWorkflowTable(w io.Writer, p func(string, ...any), workflows []workflowStats) {
	p("## CI Reliability (main branch)")
	p("")
	p("| Workflow | Runs | Passed | Failed | Pass rate |")
	p("|----------|------|--------|--------|-----------|")

	sort.Slice(workflows, func(i, j int) bool {
		ri := float64(workflows[i].runsWithFail) / math.Max(float64(workflows[i].totalRuns), 1)
		rj := float64(workflows[j].runsWithFail) / math.Max(float64(workflows[j].totalRuns), 1)
		return ri > rj
	})
	for _, ws := range workflows {
		passRate := 100.0
		if ws.totalRuns > 0 {
			passRate = float64(ws.totalRuns-ws.runsWithFail) / float64(ws.totalRuns) * 100
		}
		p("| %s | %d | %d | %d | %.0f%% |",
			ws.name, ws.totalRuns, ws.totalRuns-ws.runsWithFail, ws.runsWithFail, passRate)
	}
	p("")
}

func writeFlakyTestsTable(w io.Writer, p func(string, ...any), tests map[string]*testStats) []*testStats {
	flaky := filterFlakyTests(tests)
	if len(flaky) == 0 {
		p("## Flaky Tests")
		p("")
		p("No flaky tests detected in this period.")
		p("")
		return nil
	}

	p("## Top Flaky Tests")
	p("")
	p("Tests with failures or flaky passes, sorted by unreliability.")
	p("")
	p("| Test | Runs | Failed | Flaky | Fail %% | Primary error |")
	p("|------|------|--------|-------|--------|--------------|")

	limit := maxFlakyTestsShown
	if len(flaky) < limit {
		limit = len(flaky)
	}
	for _, ts := range flaky[:limit] {
		failPct := float64(ts.failed+ts.flakyPassed) / float64(ts.totalRuns) * 100
		p("| `%s` | %d | %d | %d | %.0f%% | %s |",
			ts.name, ts.totalRuns, ts.failed, ts.flakyPassed, failPct, primaryFingerprint(ts.fingerprints))
	}
	p("")
	return flaky
}

func writeFingerprintTable(w io.Writer, p func(string, ...any), fingerprints []fingerprintStats) {
	if len(fingerprints) == 0 {
		return
	}

	p("## Failure Fingerprints")
	p("")
	p("Error patterns observed across all failures.")
	p("")
	p("| Pattern | Occurrences | Affected tests | Example |")
	p("|---------|------------|---------------|---------|")
	for _, fp := range fingerprints {
		testNames := sortedKeys(fp.affectedTests)
		testList := strings.Join(testNames, ", ")
		if len(testList) > 80 {
			testList = testList[:77] + "..."
		}
		example := fp.example
		if len(example) > 100 {
			example = example[:97] + "..."
		}
		example = strings.ReplaceAll(example, "|", "\\|")
		p("| `%s` | %d | %d (%s) | %s |",
			fp.fingerprint, fp.occurrences, len(fp.affectedTests), testList, example)
	}
	p("")
}

func writeRecentFailuresTable(w io.Writer, p func(string, ...any), results []TestResult, repo string) {
	var failures []failureEvent
	for _, r := range results {
		if r.Outcome != "failed" && r.Outcome != "flaky-passed" {
			continue
		}
		date := r.CreatedAt
		if len(date) >= 10 {
			date = date[:10]
		}
		failures = append(failures, failureEvent{
			date:        date,
			runID:       r.RunID,
			workflow:    r.Workflow,
			shard:       r.Shard,
			test:        r.Test,
			fingerprint: r.ErrorFingerprint,
			snippet:     r.ErrorSnippet,
		})
	}
	if len(failures) == 0 {
		return
	}

	sort.Slice(failures, func(i, j int) bool {
		return failures[i].date > failures[j].date
	})

	p("## Recent Failures")
	p("")
	p("| Date | Run | Workflow | Shard | Test | Fingerprint | Error |")
	p("|------|-----|---------|-------|------|-------------|-------|")

	limit := maxRecentFailuresShown
	if len(failures) < limit {
		limit = len(failures)
	}
	for _, rf := range failures[:limit] {
		snippet := rf.snippet
		if len(snippet) > 80 {
			snippet = snippet[:77] + "..."
		}
		snippet = strings.ReplaceAll(snippet, "|", "\\|")
		snippet = strings.ReplaceAll(snippet, "\n", " ")
		fp := rf.fingerprint
		if fp == "" {
			fp = "unknown"
		}
		p("| %s | [%s](https://github.com/%s/actions/runs/%s) | %s | %s | `%s` | `%s` | %s |",
			rf.date, rf.runID, repo, rf.runID, rf.workflow, rf.shard, rf.test, fp, snippet)
	}
	p("")
}

type testStats struct {
	name             string
	totalRuns        int
	passed           int
	failed           int
	flakyPassed      int
	skipped          int
	fingerprints     map[string]int
	totalElapsed     float64
	workflowFailures map[string]int
}

type failureEvent struct {
	date        string
	runID       string
	workflow    string
	shard       string
	test        string
	fingerprint string
	snippet     string
}

type workflowStats struct {
	name         string
	totalRuns    int
	runsWithFail int
	runIDs       map[string]bool
	failedRunIDs map[string]bool
}

type fingerprintStats struct {
	fingerprint   string
	occurrences   int
	affectedTests map[string]bool
	example       string
}

func dateRange(results []TestResult) (string, string) {
	minDate, maxDate := results[0].CreatedAt, results[0].CreatedAt
	for _, r := range results {
		if r.CreatedAt < minDate {
			minDate = r.CreatedAt
		}
		if r.CreatedAt > maxDate {
			maxDate = r.CreatedAt
		}
	}
	if len(minDate) >= 10 {
		minDate = minDate[:10]
	}
	if len(maxDate) >= 10 {
		maxDate = maxDate[:10]
	}
	return minDate, maxDate
}

func computeTestStats(results []TestResult) map[string]*testStats {
	tests := map[string]*testStats{}
	for _, r := range results {
		ts, ok := tests[r.Test]
		if !ok {
			ts = &testStats{
				name:             r.Test,
				fingerprints:     map[string]int{},
				workflowFailures: map[string]int{},
			}
			tests[r.Test] = ts
		}
		ts.totalRuns++
		ts.totalElapsed += r.ElapsedS
		switch r.Outcome {
		case "passed":
			ts.passed++
		case "failed":
			ts.failed++
			if r.ErrorFingerprint != "" {
				ts.fingerprints[r.ErrorFingerprint]++
			}
			ts.workflowFailures[r.Workflow]++
		case "flaky-passed":
			ts.flakyPassed++
			if r.ErrorFingerprint != "" {
				ts.fingerprints[r.ErrorFingerprint]++
			}
			ts.workflowFailures[r.Workflow]++
		case "skipped":
			ts.skipped++
		}
	}
	return tests
}

func computeWorkflowStats(results []TestResult) []workflowStats {
	type runKey struct {
		workflow string
		runID    string
	}
	runOutcomes := map[runKey]bool{}
	for _, r := range results {
		key := runKey{r.Workflow, r.RunID}
		if r.Outcome == "failed" {
			runOutcomes[key] = true
		}
		if _, exists := runOutcomes[key]; !exists {
			runOutcomes[key] = false
		}
	}

	wfMap := map[string]*workflowStats{}
	for key, hasFail := range runOutcomes {
		ws, ok := wfMap[key.workflow]
		if !ok {
			ws = &workflowStats{
				name:         key.workflow,
				runIDs:       map[string]bool{},
				failedRunIDs: map[string]bool{},
			}
			wfMap[key.workflow] = ws
		}
		if !ws.runIDs[key.runID] {
			ws.runIDs[key.runID] = true
			ws.totalRuns++
		}
		if hasFail && !ws.failedRunIDs[key.runID] {
			ws.failedRunIDs[key.runID] = true
			ws.runsWithFail++
		}
	}

	var result []workflowStats
	for _, ws := range wfMap {
		result = append(result, *ws)
	}
	return result
}

func computeFingerprintStats(results []TestResult) []fingerprintStats {
	fpMap := map[string]*fingerprintStats{}
	for _, r := range results {
		if r.Outcome != "failed" && r.Outcome != "flaky-passed" {
			continue
		}
		fp := r.ErrorFingerprint
		if fp == "" {
			fp = "unknown"
		}
		fs, ok := fpMap[fp]
		if !ok {
			fs = &fingerprintStats{
				fingerprint:   fp,
				affectedTests: map[string]bool{},
			}
			fpMap[fp] = fs
		}
		fs.occurrences++
		fs.affectedTests[r.Test] = true
		if fs.example == "" && r.ErrorSnippet != "" {
			fs.example = r.ErrorSnippet
		}
	}

	var result []fingerprintStats
	for _, fs := range fpMap {
		result = append(result, *fs)
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].occurrences > result[j].occurrences
	})
	return result
}

func filterFlakyTests(tests map[string]*testStats) []*testStats {
	var flaky []*testStats
	for _, ts := range tests {
		if ts.failed > 0 || ts.flakyPassed > 0 {
			flaky = append(flaky, ts)
		}
	}
	sort.Slice(flaky, func(i, j int) bool {
		ri := float64(flaky[i].failed+flaky[i].flakyPassed) / float64(flaky[i].totalRuns)
		rj := float64(flaky[j].failed+flaky[j].flakyPassed) / float64(flaky[j].totalRuns)
		return ri > rj
	})
	return flaky
}

func primaryFingerprint(fps map[string]int) string {
	if len(fps) == 0 {
		return "unknown"
	}
	var best string
	bestCount := 0
	for fp, count := range fps {
		if count > bestCount {
			best = fp
			bestCount = count
		}
	}
	return "`" + best + "`"
}

func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
