// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"io"
	"math"
	"sort"
	"strings"
)

const (
	maxFlakyTestsShown     = 20
	maxRecentFailuresShown = 30
	maxSnippetDisplay      = 600
	maxTestsInList         = 8
)

func writeReport(w io.Writer, results []TestResult, metaMap map[string]RunMeta, repo string) error {
	if len(results) == 0 && len(metaMap) == 0 {
		_, err := fmt.Fprintln(w, "# CI Test Analysis Report\n\nNo test data found for the analysis period.")
		return err
	}

	minDate, maxDate := dateRangeFromMeta(metaMap)
	tests := computeTestStats(results)
	workflows := computeWorkflowStats(results, metaMap)
	fingerprints := computeFingerprintStats(results)

	p := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	p("# CI Test Analysis Report")
	p("")
	p("**Period:** %s to %s", minDate, maxDate)
	p("**Runs analyzed:** %d | **Tests tracked:** %d", len(metaMap), len(tests))
	p("")

	writeWorkflowTable(p, workflows)
	writeFlakyTestsTable(p, tests)
	writeErrorSummaryTable(p, fingerprints)
	writeFingerprintTable(p, fingerprints)
	writeRecentFailuresTable(p, results, repo)
	writeLegend(p)

	flakyCount := len(filterFlakyTests(tests))
	p("---")
	p("*Generated by CI Test Analysis · %d tests analyzed · %d flaky (%.0f%%)*",
		len(tests), flakyCount, float64(flakyCount)/math.Max(float64(len(tests)), 1)*100)

	return nil
}

func writeWorkflowTable(p func(string, ...any), workflows []workflowStats) {
	p("## CI Reliability (main branch)")
	p("")
	p("| Workflow | Runs | Clean | Flaky | Failed | Pass rate |")
	p("|----------|------|-------|-------|--------|-----------|")

	sort.Slice(workflows, func(i, j int) bool {
		ri := float64(workflows[i].runsWithIssues) / math.Max(float64(workflows[i].totalRuns), 1)
		rj := float64(workflows[j].runsWithIssues) / math.Max(float64(workflows[j].totalRuns), 1)
		return ri > rj
	})
	for _, ws := range workflows {
		passRate := 100.0
		if ws.totalRuns > 0 {
			passRate = float64(ws.totalRuns-ws.runsWithIssues) / float64(ws.totalRuns) * 100
		}
		clean := ws.totalRuns - ws.runsWithFlaky - ws.runsWithFail
		p("| %s | %d | %d | %d | %d | %.0f%% |",
			ws.name, ws.totalRuns, clean, ws.runsWithFlaky, ws.runsWithFail, passRate)
	}
	p("")
}

func writeFlakyTestsTable(p func(string, ...any), tests map[string]*testStats) {
	flaky := filterFlakyTests(tests)
	if len(flaky) == 0 {
		p("## Flaky Tests")
		p("")
		p("No flaky tests detected in this period.")
		p("")
		return
	}

	p("## Top Flaky Tests")
	p("")
	p("Tests that failed or required retries to pass, sorted by failure rate.")
	p("")
	p("- **Failures**: test failed and never passed (broken)")
	p("- **Retries**: test failed initially but passed on rerun (flaky)")
	p("")
	p("| Workflow | Test | Runs | Failures | Retries | Failure rate | Primary error |")
	p("|---------|------|------|----------|---------|-------------|--------------|")

	limit := maxFlakyTestsShown
	if len(flaky) < limit {
		limit = len(flaky)
	}
	for _, ts := range flaky[:limit] {
		failPct := float64(ts.failed+ts.flakyPassed) / float64(ts.totalRuns) * 100
		wf := primaryWorkflow(ts.workflowFailures)
		p("| %s | `%s` | %d | %d | %d | %.0f%% | %s |",
			wf, ts.name, ts.totalRuns, ts.failed, ts.flakyPassed, failPct, primaryFingerprint(ts.fingerprints))
	}
	p("")
}

// writeErrorSummaryTable aggregates from the same per-result fingerprint data
// as the Failure Fingerprints table so the numbers are always consistent.
func writeErrorSummaryTable(p func(string, ...any), fingerprints []fingerprintStats) {
	if len(fingerprints) == 0 {
		return
	}

	p("## Failures by Error Type")
	p("")
	p("| Error | Total occurrences | Affected tests |")
	p("|-------|------------------|----------------|")
	for _, fp := range fingerprints {
		testList := formatTestList(sortedKeys(fp.affectedTests))
		p("| `%s` | %d | %d (%s) |", fp.fingerprint, fp.occurrences, len(fp.affectedTests), testList)
	}
	p("")
}

func writeFingerprintTable(p func(string, ...any), fingerprints []fingerprintStats) {
	if len(fingerprints) == 0 {
		return
	}

	p("## Failure Fingerprints")
	p("")
	p("Error patterns observed across all failures.")
	p("")
	p("| Pattern | Occurrences | Affected tests | Example |")
	p("|---------|------------|---------------|---------|")
	for _, fp := range fingerprints {
		testList := formatTestList(sortedKeys(fp.affectedTests))
		example := fp.example
		if len(example) > maxSnippetDisplay {
			example = example[:maxSnippetDisplay-3] + "..."
		}
		example = strings.ReplaceAll(example, "|", "\\|")
		example = strings.ReplaceAll(example, "\n", " ")
		p("| `%s` | %d | %d (%s) | %s |",
			fp.fingerprint, fp.occurrences, len(fp.affectedTests), testList, example)
	}
	p("")
}

func writeRecentFailuresTable(p func(string, ...any), results []TestResult, repo string) {
	var failures []failureEvent
	for _, r := range results {
		if r.Outcome != "failed" && r.Outcome != "flaky-passed" {
			continue
		}
		failures = append(failures, failureEvent{
			runID:       r.RunID,
			workflow:    r.Workflow,
			test:        r.Test,
			fingerprint: r.ErrorFingerprint,
			snippet:     r.ErrorSnippet,
		})
	}
	if len(failures) == 0 {
		return
	}

	sort.Slice(failures, func(i, j int) bool {
		if failures[i].fingerprint != failures[j].fingerprint {
			return failures[i].fingerprint < failures[j].fingerprint
		}
		return failures[i].test < failures[j].test
	})

	p("## Failure Details")
	p("")
	p("| Run | Workflow | Test | Fingerprint | Error |")
	p("|-----|---------|------|-------------|-------|")

	limit := maxRecentFailuresShown
	if len(failures) < limit {
		limit = len(failures)
	}
	for _, rf := range failures[:limit] {
		snippet := rf.snippet
		if len(snippet) > maxSnippetDisplay {
			snippet = snippet[:maxSnippetDisplay-3] + "..."
		}
		snippet = strings.ReplaceAll(snippet, "|", "\\|")
		snippet = strings.ReplaceAll(snippet, "\n", " ")
		fp := rf.fingerprint
		if fp == "" {
			fp = "unknown"
		}
		p("| [%s](https://github.com/%s/actions/runs/%s) | %s | `%s` | `%s` | %s |",
			rf.runID, repo, rf.runID, rf.workflow, rf.test, fp, snippet)
	}
	p("")
}

func writeLegend(p func(string, ...any)) {
	// Sorted alphabetically by pattern name.
	p("## Fingerprint Legend")
	p("")
	p("| Pattern | Description |")
	p("|---------|-------------|")
	p("| `cancelled` | Run cancelled or interrupted — typically a job-level timeout |")
	p("| `connection-refused` | Service not reachable — likely not yet started or crashed |")
	p("| `data-race` | Go race detector found a data race (`-race` flag) |")
	p("| `disk-full` | Runner ran out of disk space |")
	p("| `docker-error` | Docker daemon error — image pull, OCI runtime, or daemon connectivity |")
	p("| `exit-error` | Non-zero exit code with no more specific pattern matched |")
	p("| `oom-killed` | Process killed by signal — typically out of memory |")
	p("| `panic` | Unrecovered Go panic |")
	p("| `port-conflict` | Docker port already allocated or address in use — container startup collision |")
	p("| `timeout` | Test or context deadline exceeded |")
	p("| `unknown` | No error output captured |")
	p("| `unknown-XXXXXXXX` | Unrecognized error — hash groups identical unknown failures together |")
	p("")
}

// formatTestList renders test names as backticked, comma-separated list,
// truncating by count to avoid breaking markdown with partial names.
func formatTestList(names []string) string {
	if len(names) <= maxTestsInList {
		backticked := make([]string, len(names))
		for i, t := range names {
			backticked[i] = "`" + t + "`"
		}
		return strings.Join(backticked, ", ")
	}
	backticked := make([]string, maxTestsInList)
	for i := range maxTestsInList {
		backticked[i] = "`" + names[i] + "`"
	}
	return strings.Join(backticked, ", ") + fmt.Sprintf(" +%d more", len(names)-maxTestsInList)
}

type testStats struct {
	name             string
	totalRuns        int
	passed           int
	failed           int
	flakyPassed      int
	skipped          int
	fingerprints     map[string]int
	totalElapsed     float64
	workflowFailures map[string]int
}

type failureEvent struct {
	runID       string
	workflow    string
	test        string
	fingerprint string
	snippet     string
}

type workflowStats struct {
	name           string
	totalRuns      int
	runsWithFail   int // runs with at least one hard failure
	runsWithFlaky  int // runs with flaky-passed but no hard failure
	runsWithIssues int // runsWithFail + runsWithFlaky
	runIDs         map[string]bool
	failedRunIDs   map[string]bool
	flakyRunIDs    map[string]bool
}

type fingerprintStats struct {
	fingerprint   string
	occurrences   int
	affectedTests map[string]bool
	example       string
}

func dateRangeFromMeta(metaMap map[string]RunMeta) (string, string) {
	var minDate, maxDate string
	for _, rm := range metaMap {
		d := rm.CreatedAt
		if len(d) >= 10 {
			d = d[:10]
		}
		if d == "" {
			continue
		}
		if minDate == "" || d < minDate {
			minDate = d
		}
		if maxDate == "" || d > maxDate {
			maxDate = d
		}
	}
	return minDate, maxDate
}

func computeTestStats(results []TestResult) map[string]*testStats {
	tests := map[string]*testStats{}
	for _, r := range results {
		ts, ok := tests[r.Test]
		if !ok {
			ts = &testStats{
				name:             r.Test,
				fingerprints:     map[string]int{},
				workflowFailures: map[string]int{},
			}
			tests[r.Test] = ts
		}
		ts.totalRuns++
		ts.totalElapsed += r.ElapsedS
		switch r.Outcome {
		case "passed":
			ts.passed++
		case "failed":
			ts.failed++
			if r.ErrorFingerprint != "" {
				ts.fingerprints[r.ErrorFingerprint]++
			}
			ts.workflowFailures[r.Workflow]++
		case "flaky-passed":
			ts.flakyPassed++
			if r.ErrorFingerprint != "" {
				ts.fingerprints[r.ErrorFingerprint]++
			}
			ts.workflowFailures[r.Workflow]++
		case "skipped":
			ts.skipped++
		}
	}
	return tests
}

// computeWorkflowStats builds workflow reliability stats from both test results
// and run metadata. This ensures job-only workflows (which produce no TestResult
// entries) still appear in the reliability table.
func computeWorkflowStats(results []TestResult, metaMap map[string]RunMeta) []workflowStats {
	type runKey struct {
		workflow string
		runID    string
	}
	// Track per-run: hasFail and hasFlaky separately.
	type runState struct {
		hasFail  bool
		hasFlaky bool
	}
	runStates := map[runKey]*runState{}

	// Seed from metaMap so every collected run is represented.
	for _, rm := range metaMap {
		key := runKey{rm.Workflow, rm.RunID}
		rs := &runState{}
		// For runs without test-level data, use the run conclusion.
		switch rm.Conclusion {
		case "failure", "timed_out", "cancelled":
			rs.hasFail = true
		}
		runStates[key] = rs
	}

	// Override with test-level data when available.
	for _, r := range results {
		key := runKey{r.Workflow, r.RunID}
		rs, ok := runStates[key]
		if !ok {
			rs = &runState{}
			runStates[key] = rs
		}
		if r.Outcome == "failed" {
			rs.hasFail = true
		}
		if r.Outcome == "flaky-passed" {
			rs.hasFlaky = true
		}
	}

	wfMap := map[string]*workflowStats{}
	for key, rs := range runStates {
		ws, ok := wfMap[key.workflow]
		if !ok {
			ws = &workflowStats{
				name:         key.workflow,
				runIDs:       map[string]bool{},
				failedRunIDs: map[string]bool{},
				flakyRunIDs:  map[string]bool{},
			}
			wfMap[key.workflow] = ws
		}
		if !ws.runIDs[key.runID] {
			ws.runIDs[key.runID] = true
			ws.totalRuns++
		}
		if rs.hasFail && !ws.failedRunIDs[key.runID] {
			ws.failedRunIDs[key.runID] = true
			ws.runsWithFail++
			ws.runsWithIssues++
		} else if rs.hasFlaky && !ws.flakyRunIDs[key.runID] {
			ws.flakyRunIDs[key.runID] = true
			ws.runsWithFlaky++
			ws.runsWithIssues++
		}
	}

	var result []workflowStats
	for _, ws := range wfMap {
		result = append(result, *ws)
	}
	return result
}

func computeFingerprintStats(results []TestResult) []fingerprintStats {
	fpMap := map[string]*fingerprintStats{}
	for _, r := range results {
		if r.Outcome != "failed" && r.Outcome != "flaky-passed" {
			continue
		}
		fp := r.ErrorFingerprint
		if fp == "" {
			fp = "unknown"
		}
		fs, ok := fpMap[fp]
		if !ok {
			fs = &fingerprintStats{
				fingerprint:   fp,
				affectedTests: map[string]bool{},
			}
			fpMap[fp] = fs
		}
		fs.occurrences++
		fs.affectedTests[r.Test] = true
		if fs.example == "" && r.ErrorSnippet != "" {
			fs.example = r.ErrorSnippet
		}
	}

	var result []fingerprintStats
	for _, fs := range fpMap {
		result = append(result, *fs)
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].occurrences > result[j].occurrences
	})
	return result
}

func filterFlakyTests(tests map[string]*testStats) []*testStats {
	var flaky []*testStats
	for _, ts := range tests {
		if ts.failed > 0 || ts.flakyPassed > 0 {
			flaky = append(flaky, ts)
		}
	}
	sort.Slice(flaky, func(i, j int) bool {
		ri := float64(flaky[i].failed+flaky[i].flakyPassed) / float64(flaky[i].totalRuns)
		rj := float64(flaky[j].failed+flaky[j].flakyPassed) / float64(flaky[j].totalRuns)
		return ri > rj
	})
	return flaky
}

func primaryFingerprint(fps map[string]int) string {
	if len(fps) == 0 {
		return "unknown"
	}
	var best string
	bestCount := 0
	for fp, count := range fps {
		if count > bestCount || (count == bestCount && fp < best) {
			best = fp
			bestCount = count
		}
	}
	return "`" + best + "`"
}

func primaryWorkflow(wfs map[string]int) string {
	if len(wfs) == 0 {
		return ""
	}
	var best string
	bestCount := 0
	for wf, count := range wfs {
		if count > bestCount || (count == bestCount && wf < best) {
			best = wf
			bestCount = count
		}
	}
	return best
}

func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
