#!/bin/bash
# Week 7 - Day 7: 测试 HTTP 追踪器并对比 OBI
echo "=== HTTP 追踪器测试 ==="
echo ""
echo "步骤 1: 启动一个测试 HTTP 服务"
echo "  python3 -m http.server 8080 &"
echo ""
echo "步骤 2: 启动你的追踪器"
echo "  sudo ./http-tracer"
echo ""
echo "步骤 3: 发送测试请求"
echo "  curl http://localhost:8080/"
echo "  curl http://localhost:8080/not-found"
echo "  wrk -t2 -c10 -d5s http://localhost:8080/"
echo ""
echo "步骤 4: 查看 Prometheus metrics"
echo "  curl http://localhost:9090/metrics | grep http_request"
echo ""
echo "步骤 5: 对比 OBI 的输出"
echo "  参考: bpf/generictracer/protocol_http.h"
echo "  OBI 能检测更多: HTTP/2, gRPC, 请求体, Content-Type 等"
