# TODO: if zizmor doesn't pass, don't run any other action
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: gh-actions-security-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  zizmor:
    name: Zizmor Security Analysis
    permissions:
      contents: read # for actions/checkout
      security-events: write # for zizmor to upload SARIF results
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@68c7b2f0ef9cd9c1e2b71d3018f63127be189578 # v0.14.0
