name: Lint (Darwin)

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["main", "release-*"]
    paths:
      - ".github/workflows/lint_darwin.yml"
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "bpf/**"
      - "cmd/**"
      - "configs/**"
      - "internal/**"
      - "pkg/**"
      - "scripts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  generate-bpf:
    name: docker-generate on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "go.mod"
          cache: "false"

      - name: Generate BPF files
        run: make docker-generate

      - name: Upload generated BPF files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          # prevent cache poisoning by using the SHA of the commit
          name: bpf-generated-${{ github.sha }}
          path: |
            **/*_bpfel.go
            **/*_bpfel.o
          retention-days: 1

  # macOS runners do not have docker installed, so we need to download the generated BPF files from the Linux runner.
  lint-darwin:
    name: lint on macOS
    needs: generate-bpf
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "go.mod"
          cache: "false"

      - name: Download generated BPF files
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: bpf-generated-${{ github.sha }}

      - name: Run lint
        run: make lint
