name: PR OATS test

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions:
  contents: read
  # Required for codecov
  checks: write
  pull-requests: write
  # Required for uploading artifacts
  actions: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.24' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          cache: 'false'
          go-version: ${{ matrix.go }}
      - name: Clean up disk space
        run: |
          docker system prune -af
          docker volume prune -f
      - name: Run oats tests
        run: make oats-test
      - name: Upload oats test logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: Oats test logs
          path: test/oats/*/build/*
      - name: Report coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./testoutput/itest-covdata.txt
          flags: oats-test
