name: Update offsets
on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Required for creating PRs
  pull-requests: write  # Required for creating PRs

jobs:
  UpdateOffsets:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false
    - name: "Update Go"
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        cache: 'false'
        go-version: '>=1.24'
        check-latest: true
    - name: "Update offsets"
      run: make update-offsets
    - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
      id: generate-token
      with:
        app-id: ${{ vars.OTELBOT_APP_ID }}
        private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
    - name: "Create/update PR"
      uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
      with:
        commit-message: Automatic update of offsets.json
        title: Automatic update of offsets.json
        body: The offsets have been updated by go-offsets-tracker
        base: main
        branch: otelbot/offset-content-auto-update
        labels: automated-pr
        delete-branch: true
        committer: otelbot <197425009+otelbot@users.noreply.github.com>
        author: otelbot <197425009+otelbot@users.noreply.github.com>
        token: ${{ steps.generate-token.outputs.token }}
        sign-commits: true
