name: Update offsets
on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Required for creating PRs

jobs:
  UpdateOffsets:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: true
    - name: "Update Go"
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        cache: 'false'
        go-version: '>=1.24'
        check-latest: true
    - name: "Update offsets"
      run: make update-offsets
    - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
      id: generate-token
      with:
        app-id: ${{ vars.OTELBOT_APP_ID }}
        private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
    - name: "Create/update PR"
      env:
        # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        message="Automatic update of offsets.json
        body="The offsets have been updated by go-offsets-tracker"
        branch="otelbot/offset-content-auto-update"

        git config user.name otelbot
        git config user.email 197425009+otelbot@users.noreply.github.com
  
        git checkout -b $branch
        git commit -a -m "$message"
        git push --set-upstream origin $branch
        gh pr create --title "$message" \
                     --body "$body" \
                     --base main
