name: Pull request integration tests on VM

on:
  workflow_call:
    inputs:
      arch:
        description: 'Target architecture to run the tests'
        required: true
        type: string
      kernel-version:
        description: 'Kernel version to use when running the tests'
        required: true
        type: string
      timeout-minutes:
        description: 'Timeout in minutes before the test is terminated'
        required: false
        type: number
        default: 60

permissions:
  contents: read
  # Required for codecov
  checks: write
  pull-requests: write
  # Required for uploading artifacts
  actions: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Clean up disk space
        run: |
          docker system prune -af
          docker volume prune -f
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils qemu-system-x86
      - name: Run VM integration tests
        run: |
          make docker-generate
          sudo make -C test/vm KERNEL_VER=${KERNEL_VERSION} ARCH=${ARCH} && [ -f testoutput/success ]
        env:
          ARCH: ${{ inputs.arch }}
          KERNEL_VERSION: ${{ inputs.kernel-version }}
        timeout-minutes: ${{ inputs.timeout-minutes }}
      - name: Upload integration test logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: Test Logs
          path: |
            testoutput/*.log
            testoutput/kind
      - name: Report coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          ARCH: ${{ inputs.arch }}
          KERNEL_VERSION: ${{ inputs.kernel-version }}
        with:
          file: ./testoutput/itest-covdata.txt
          flags: integration-test-vm-${ARCH}-${KERNEL_VERSION}