# Dockerfile that will build a container that runs python flask with gunicorn on port 7770
FROM python:3.14.3-slim@sha256:486b8092bfb12997e10d4920897213a06563449c951c5506c2a2cfaf591c599f
EXPOSE 7770
RUN pip install flask gunicorn requests
# Alternative: RUN pip install flask uwsgi

# Set the working directory to /build
WORKDIR /

# Copy the source code into the image for building
COPY internal/test/integration/components/pythonserver .

CMD ["bash", "/run.sh"]
# CMD uwsgi --http 0.0.0.0:7770 --master -p 4 -w main:app
